### ISSUE TITLE
Plugin fails to initialize at startup

### ISSUE THREAD

**Issue by mofoni** [crystian/ComfyUI-Crystools#101]
**Bug**  
right after loading extra model paths Crystools reports `AttributeError: type object 'DataSource' has no attribute 'arch_string_raw'` and fails to load

**To Reproduce**  
start up ComfyUI Version 2440[d96547](2024-08-01) with Manager: V2.48.4 and try to load with the most recent version of Crystools

**Console Log:**  

Startup info:
```
** Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
```
```
Total VRAM 24564 MB, total RAM 64655 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch cross attention
```
.... now comes the Error:
```
[Crystools INFO] Crystools version: 1.16.5
Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\nodes.py", line 1936, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools\__init__.py", line 24, in <module>
    from .server import *
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools\server\__init__.py", line 1, in <module>
    from .monitor import *
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools\server\monitor.py", line 4, in <module>
    from ..general import cmonitor
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools\general\__init__.py", line 1, in <module>
    from .monitor import *
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools\general\monitor.py", line 66, in <module>
    cmonitor = CMonitor(1, True, True, True, True, True)
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools\general\monitor.py", line 20, in __init__
    self.hardwareInfo = CHardwareInfo(switchCPU, switchGPU, switchHDD, switchRAM, switchVRAM)
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools\general\hardware.py", line 41, in __init__
    self.print_sys_info()
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools\general\hardware.py", line 73, in print_sys_info
    specArch = 'Arch: ' + DataSource.arch_string_raw
AttributeError: type object 'DataSource' has no attribute 'arch_string_raw'

Cannot import C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools module for custom nodes: type object 'DataSource' has no attribute 'arch_string_raw'
```
```
### Loading: ComfyUI-Manager (V2.48.4)
### ComfyUI Revision: 2440 [d965474a] | Released on '2024-08-01'
```
additional info if relevant: i run ComfyUI inside a virtula Python VENV, due to Verison conflicts with other software i use.

**Comment by Lucas-the-Silly** [comment]
Same as me.

**Comment by DavidSnow1** [comment]
Same.

**Comment by mno1337** [comment]
same

**Comment by crystian** [comment]
which SO do you have?

**Comment by crystian** [comment]
and which processor do you have?

**Comment by crystian** [comment]
update and try again please
