### ISSUE TITLE
AMD gpu issues / on both main and AMD branch

### ISSUE THREAD

**Issue by maurus56** [crystian/ComfyUI-Crystools#111]
**Describe the bug**  
Fail to init gpu packages, am i missing something? It was working perfectly until i tried installing this library and prob messed up the package versions i had 

**To Reproduce**  
__Please attach a workflow file to make it easier for others to reproduce the error!__

**Expected behavior**  

**Screenshots**  

**Error in console:**  
```
Traceback (most recent call last):
  File "/home/rick/Documents/flux/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 639, in _raw_device_count_amdsmi
    amdsmi.amdsmi_init()
    ^^^^^^
NameError: name 'amdsmi' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rick/Documents/flux/ComfyUI/main.py", line 229, in <module>
    cuda_malloc_warning()
  File "/home/rick/Documents/flux/ComfyUI/main.py", line 94, in cuda_malloc_warning
    device_name = comfy.model_management.get_torch_device_name(device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rick/Documents/flux/ComfyUI/comfy/model_management.py", line 263, in get_torch_device_name
    return "{} {} : {}".format(device, torch.cuda.get_device_name(device), allocator_backend)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rick/Documents/flux/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 435, in get_device_name
    return get_device_properties(device).name
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rick/Documents/flux/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 467, in get_device_properties
    if device < 0 or device >= device_count():
                               ^^^^^^^^^^^^^^
  File "/home/rick/Documents/flux/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 842, in device_count
    nvml_count = _device_count_amdsmi() if torch.version.hip else _device_count_nvml()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rick/Documents/flux/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 764, in _device_count_amdsmi
    raw_cnt = _raw_device_count_amdsmi()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rick/Documents/flux/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 640, in _raw_device_count_amdsmi
    except amdsmi.AmdSmiException as e:
           ^^^^^^
NameError: name 'amdsmi' is not defined
```

**Versions:**  
Copy the output of the console (4 parts), like this:
```
** Python version: 3.11.9 (main, Nov 10 2011, 15:00:00) [GCC 13.2.0]
```
```
Total VRAM 16368 MB, total RAM 31303 MB
pytorch version: 2.4.0+rocm6.1
Set vram state to: LOW_VRAM
```
```
[Crystools INFO] Crystools version: 1.16.6
[Crystools INFO] CPU: AMD Ryzen 7 7700X 8-Core Processor - Arch: x86_64 - OS: Linux 6.9.3-76060903-generic
[Crystools ERROR] Could not init pynvml (Nvidia).NVML Shared Library Not Found
[Crystools ERROR] Could not pick default device.name 'amdsmi' is not defined
[Crystools WARNING] No GPU with CUDA detected.
```
```
[Crystools INFO] Crystools version: 1.16.4
[Crystools INFO] CPU: AMD Ryzen 7 7700X 8-Core Processor - Arch: x86_64 - OS: Linux 6.9.3-76060903-generic
[Crystools ERROR] Could not init pynvml (Nvidia).NVML Shared Library Not Found
cat: /sys/module/amdgpu/initstate: No such file or directory
[Crystools ERROR] Could not init pyrsmi (AMD).ROCm driver initilization failed
[Crystools ERROR] Could not pick default device.name 'amdsmi' is not defined
[Crystools WARNING] No GPU with CUDA detected.
```
```
### Loading: ComfyUI-Manager (V2.50.2)
### ComfyUI Revision: 2617 [2ca8f6e2] | Released on '2024-08-26'
```

**Additional context**

**Comment by t3dc** [comment]
Hitting this same issue as well.

**Comment by maurus56** [comment]
Seems like the issue is related to the torch version, just downgrade and it should be fine:
```
pip install torch==2.3.0+rocm6.0 torchvision==0.18.0+rocm6.0 torchaudio==2.3.0+rocm6.0 --index-url https://download.pytorch.org/whl/rocm6.0
```

**Comment by jnolck** [comment]
I had this issue too. The problem is with pyrsmi not with Crystaltools. I had to hardcode the path to my rocm_smi lib in pyrsmi.  

I tried doing the right way by setting $ROCM_PATH but it wouldn't work with the combinations I tried. 

I commented rocm_path and rocm_lib_path and then added a new line below. 

rocm_lib_path = "/usr/lib64/librocm_smi64.so"

Crystaltools is displaying gpu, vram, and temp showing  in comfy now.

**Comment by chimLec** [comment]
A slight bug in rocml.py causes the problem when rocm_lip_path is set by joining rocm_path and f'lib/{LIBROCM_NAME}' the preceding '/' is omitted. It should be: f'/lib/{LIBROCM_NAME}'. The omission causes the path to be invalid and not work.

**Comment by jnolck** [comment]
chimLec. ROCM isn't installed on /opt/rocm/ in fedora. It's in /usr. I'm pretty sure I tried setting ROCM_PATH to /usr and /usr/ to no avail. 

This is in my .bashrc. 

```export HIP_PATH=/usr
export ROCM_PATH=/usr
export HIP_PLATFORM=amd
export HIP_RUNTIME=rocclr
export HIP_COMPILER=clang
export HIP_CLANG_PATH=/usr/lib64/llvm18/bin
export DEVICE_LIB_PATH=/usr/lib64/rocm/llvm/lib/clang/18/amdgcn/bitcode/
export HIP_DEVICE_LIB_PATH=/usr/lib64/rocm/llvm/lib/clang/18/amdgcn/bitcode/
export HSA_PATH=/usr/hsa
export LLVM_PATH=/usr
```
This is the offending code in prysmi. It's in rocml.py

```
def _find_lib_rocm():
    rocm_path = os.environ.get('ROCM_PATH', '/opt/rocm')
    rocm_lib_path = join(rocm_path, f'lib/{LIBROCM_NAME}')
    return rocm_lib_path if isfile(rocm_lib_path) else ''
```
LIBROCM_NAME = 'librocm_smi64.so'

in order for it to work for me I think it would have to be ```rocm_lib_path = join(rocm_path, f'lib64/{LIBROCM_NAME}')```.
I'm not sure how that would be fixed though, because that would break for everyone that does have librocm_smi64.so in /opt/rocm/lib/librocm_smi64.so. 

I just hard coded it for it to work for me. 

```
    #rocm_path = os.environ.get('ROCM_PATH', '/opt/rocm')
    #rocm_lib_path = join(rocm_path, f'lib/{LIBROCM_NAME}')
    rocm_lib_path = "/usr/lib64/librocm_smi64.so"
    return rocm_lib_path if isfile(rocm_lib_path) else ''
```

**Comment by Frozen-byte** [comment]
I could solve this with 
```
# fix Crystools not finding amdsmi
export ROCM_PATH=/home/frozen_byte/IdeaProjects/ComfyUI/venv/lib/python3.12/site-packages/torch
```
in my startscript (your path will be different ofc)
