### ISSUE TITLE
Cannot import ComfyUI/custom_nodes/ComfyUI-Crystools

### ISSUE THREAD

**Issue by LGQRL** [crystian/ComfyUI-Crystools#120]
[Crystools INFO] Crystools version: 1.16.6
Traceback (most recent call last):
  File "/Volumes/Elements/project/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Volumes/Elements/project/ComfyUI/custom_nodes/ComfyUI-Crystools/__init__.py", line 24, in <module>
    from .server import *
  File "/Volumes/Elements/project/ComfyUI/custom_nodes/ComfyUI-Crystools/server/__init__.py", line 1, in <module>
    from .monitor import *
  File "/Volumes/Elements/project/ComfyUI/custom_nodes/ComfyUI-Crystools/server/monitor.py", line 4, in <module>
    from ..general import cmonitor
  File "/Volumes/Elements/project/ComfyUI/custom_nodes/ComfyUI-Crystools/general/__init__.py", line 1, in <module>
    from .monitor import *
  File "/Volumes/Elements/project/ComfyUI/custom_nodes/ComfyUI-Crystools/general/monitor.py", line 5, in <module>
    from .hardware import CHardwareInfo
  File "/Volumes/Elements/project/ComfyUI/custom_nodes/ComfyUI-Crystools/general/hardware.py", line 3, in <module>
    import cpuinfo
  File "/opt/miniconda3/envs/comfyui/lib/python3.10/site-packages/cpuinfo/__init__.py", line 7, in <module>
    from cpuinfo.cpuinfo import *
  File "/opt/miniconda3/envs/comfyui/lib/python3.10/site-packages/cpuinfo/cpuinfo.py", line 1842, in <module>
    _check_arch()
  File "/opt/miniconda3/envs/comfyui/lib/python3.10/site-packages/cpuinfo/cpuinfo.py", line 1798, in _check_arch
    raise Exception("py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.")
Exception: py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.

Cannot import /Volumes/Elements/project/ComfyUI/custom_nodes/ComfyUI-Crystools module for custom nodes: py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.

**Comment by crystian** [comment]
> py-cpuinfo currently only works on X86 and some PPC and ARM CPUs

¯\_(ツ)_/¯
