### ISSUE TITLE
Install issue on AMD/Linux

### ISSUE THREAD

**Issue by brunoorsolon** [crystian/ComfyUI-Crystools#121]
**Describe the bug**  
I tried installing following the Linux/AMD method and when i load ComfyUI, Crystools is not available

**To Reproduce**  
Can't use in workflows. It fails to load at start.

**Expected behavior**  
Enable crystools nodes

**Screenshots**  
![image](https://github.com/user-attachments/assets/52f09a36-e9b8-4fc6-9472-6fe428530499)

**Error in console:**  
```
Total VRAM 12272 MB, total RAM 63899 MB
pytorch version: 2.6.0.dev20240919+rocm6.2
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 7700 XT : native
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
[Prompt Server] web root: /home/linuxai/ComfyUI/web
Adding extra search path checkpoints /home/linuxai/StableDiffusion/stable-diffusion-webui/models/Stable-diffusion
Adding extra search path configs /home/linuxai/StableDiffusion/stable-diffusion-webui/models/Stable-diffusion
Adding extra search path vae /home/linuxai/StableDiffusion/stable-diffusion-webui/models/VAE
Adding extra search path loras /home/linuxai/StableDiffusion/stable-diffusion-webui/models/Lora
Adding extra search path loras /home/linuxai/StableDiffusion/stable-diffusion-webui/models/LyCORIS
Adding extra search path upscale_models /home/linuxai/StableDiffusion/stable-diffusion-webui/models/ESRGAN
Adding extra search path upscale_models /home/linuxai/StableDiffusion/stable-diffusion-webui/models/RealESRGAN
Adding extra search path upscale_models /home/linuxai/StableDiffusion/stable-diffusion-webui/models/SwinIR
Adding extra search path embeddings /home/linuxai/StableDiffusion/stable-diffusion-webui/embeddings
Adding extra search path hypernetworks /home/linuxai/StableDiffusion/stable-diffusion-webui/models/hypernetworks
Adding extra search path controlnet /home/linuxai/StableDiffusion/stable-diffusion-webui/models/ControlNet
/home/linuxai/miniconda3/envs/comfy/lib/python3.10/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
[Crystools INFO] Crystools version: 1.16.4
Traceback (most recent call last):
  File "/home/linuxai/ComfyUI/nodes.py", line 1994, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/linuxai/ComfyUI/custom_nodes/ComfyUI-Crystools/__init__.py", line 18, in <module>
    from .nodes.image import CImagePreviewFromImage, CImageLoadWithMetadata, CImageGetResolution, CImagePreviewFromMetadata, \
  File "/home/linuxai/ComfyUI/custom_nodes/ComfyUI-Crystools/nodes/image.py", line 12, in <module>
    from PIL.ExifTags import TAGS, GPSTAGS, IFD
ImportError: cannot import name 'IFD' from 'PIL.ExifTags' (/home/linuxai/miniconda3/envs/comfy/lib/python3.10/site-packages/PIL/ExifTags.py)

Cannot import /home/linuxai/ComfyUI/custom_nodes/ComfyUI-Crystools module for custom nodes: cannot import name 'IFD' from 'PIL.ExifTags' (/home/linuxai/miniconda3/envs/comfy/lib/python3.10/site-packages/PIL/ExifTags.py)

Import times for custom nodes:
   0.0 seconds: /home/linuxai/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds (IMPORT FAILED): /home/linuxai/ComfyUI/custom_nodes/ComfyUI-Crystools

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Versions:**  
Copy the output of the console (4 parts), like this:
I don't really have this message of the python version.

python -V shows:
```
** Python 3.10.14
```
```
Total VRAM 12272 MB, total RAM 63899 MB
Set vram state to: NORMAL_VRAM
```
```
[Crystools INFO] Crystools version: 1.16.4
```
```
### Loading: ComfyUI-Manager (V1.25.3)
### ComfyUI Revision: 1886 [6a10640f] | Released on '2024-01-08'
```

**Additional context**  
Installed following this instructions: https://github.com/crystian/ComfyUI-Crystools?tab=readme-ov-file#for-amd-users

**Comment by crystian** [comment]
try to use the AMD branch please, follow the instructions on readme for AMD
Let me know if it works, thanks!
