### ISSUE TITLE
Support Jetson AGX Orin 

### ISSUE THREAD

**Issue by johnnynunez** [crystian/ComfyUI-Crystools#141]
/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
[Prompt Server] web root: /opt/ComfyUI/web
/usr/local/lib/python3.10/dist-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
NumExpr defaulting to 12 threads.
[Crystools INFO] Crystools version: 1.20.0
[Crystools INFO] CPU: ARMv8 Processor rev 1 (v8l) - Arch: aarch64 - OS: Linux 5.15.148-tegra
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) Orin (nvgpu)
[Crystools INFO] NVIDIA Driver: 540.4.0
[Crystools ERROR] Could not get GPU utilization.Not Supported
[Crystools ERROR] Monitor of GPU is turning off (not on UI!)
Exception in thread Thread-5 (startMonitorLoop)here: /opt/ComfyUI/custom_nodes/ComfyUI-tbox:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    Using ckpts path: /opt/ComfyUI/custom_nodes/ComfyUI-tbox/../../models/annotatorself.run()

Using symlinks: False  File "/usr/lib/python3.10/threading.py", line 953, in run

Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']
    self._target(*self._args, **self._kwargs)
  File "/opt/ComfyUI/custom_nodes/ComfyUI-Crystools/general/monitor.py", line 31, in startMonitorLoop
    asyncio.run(self.MonitorLoop())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/ComfyUI/custom_nodes/ComfyUI-Crystools/general/monitor.py", line 35, in MonitorLoop
    data = self.hardwareInfo.getStatus()
  File "/opt/ComfyUI/custom_nodes/ComfyUI-Crystools/general/hardware.py", line 114, in getStatus
    getStatus = self.GPUInfo.getStatus()
  File "/opt/ComfyUI/custom_nodes/ComfyUI-Crystools/general/gpu.py", line 151, in getStatus
    memory = self.deviceGetMemoryInfo(deviceHandle)
  File "/opt/ComfyUI/custom_nodes/ComfyUI-Crystools/general/gpu.py", line 241, in deviceGetMemoryInfo
    mem = pynvml.nvmlDeviceGetMemoryInfo(deviceHandle)
  File "/usr/local/lib/python3.10/dist-packages/pynvml/nvml.py", line 2440, in nvmlDeviceGetMemoryInfo
    _nvmlCheckReturn(ret)
  File "/usr/local/lib/python3.10/dist-packages/pynvml/nvml.py", line 833, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.nvml.NVMLError_NotSupported: Not Supported
generated new fontManager

**Comment by johnnynunez** [comment]
pynvml only works in PC
jtop is done for jetson
https://github.com/rbonghi/jetson_stats

**Comment by Sotatek-TungDinh** [comment]
Hello, I am currently looking to customize a Jetson AGX Orin 64 board. Could you please provide me with the process to do this?

**Comment by johnnynunez** [comment]
> Hello, I am currently looking to customize a Jetson AGX Orin 64 board. Could you please provide me with the process to do this?

https://github.com/johnnynunez/ComfyUI-Crystools

**Comment by crystian** [comment]
I'll check it over the weekend, but please make a pull from the dev or main and check only the changes on your PR. Thanks!

**Comment by crystian** [comment]
Please update with main @johnnynunez

**Comment by johnnynunez** [comment]
I have to update the code

**Comment by crystian** [comment]
ah ok, thanks

**Comment by johnnynunez** [comment]
> ah ok, thanks

Yes. I meet with the jetson-stats guy. 
When I have I will fix it to take temp etc

**Comment by johnnynunez** [comment]
done
