### ISSUE TITLE
Error after install from Comfy Manager

### ISSUE THREAD

**Issue by trashie65** [crystian/ComfyUI-Crystools#26]
[Crystools INFO] Crystools version: 1.10.1
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools\__init__.py", line 18, in <module>
    from .nodes.image import CImagePreviewFromImage, CImageLoadWithMetadata, CImageGetResolution, CImagePreviewFromMetadata, \
  File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools\nodes\image.py", line 11, in <module>
    from PIL.ExifTags import TAGS, GPSTAGS, IFD
ImportError: cannot import name 'IFD' from 'PIL.ExifTags' (D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\PIL\ExifTags.py)

Cannot import D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools module for custom nodes: cannot import name 'IFD' from 'PIL.ExifTags' (D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\PIL\ExifTags.py)

**Comment by crystian** [comment]
ummm, I'm not sure how the installation is with portable, but I see it does not install requirements

Please uninstall (crystools), update all, and install again.

On the other hand, you can run the requirements [manually](https://github.com/crystian/ComfyUI-Crystools?tab=readme-ov-file#install-from-github) with
```
pip install -r requirements.txt
```
Let me know if it works, thanks

**Comment by crystian** [comment]
I will close this issue, if it happens, please fill the form in a new [issue](https://github.com/crystian/ComfyUI-Crystools/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=)
