### ISSUE TITLE
Monitor doesn't show up

### ISSUE THREAD

**Issue by nothingness6** [crystian/ComfyUI-Crystools#42]
**Describe the bug**  
The monitor doesn't show up since transferred the custom nodes. 

**To Reproduce**  
__Please attach a workflow file to make it easier for others to reproduce the error!__
I transferred custom_nodes folder from Stability Matrix ComfyUI to ComfyUI_portable, and then the issue happened. 

**Expected behavior**  
The monitor should be shown up. 

**Screenshots**  

**Error in console:**  
If applicable, add the error message from the console.
```
Cannot import M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: cannot import name 'devices' from 'modules' (M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)
Traceback (most recent call last):
  File "M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_vid2vid\__init__.py", line 8, in <module>
    from .sd import load_checkpoint_guess_config, load_lora_for_models
  File "M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_vid2vid\sd.py", line 3, in <module>
    from comfy.sd import load_model_weights, ModelPatcher, VAE, CLIP, model_lora_keys_unet, model_lora_keys_clip
ImportError: cannot import name 'ModelPatcher' from 'comfy.sd' (M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\comfy\sd.py)

Cannot import M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_vid2vid module for custom nodes: cannot import name 'ModelPatcher' from 'comfy.sd' (M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\comfy\sd.py)
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Traceback (most recent call last):
  File "M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\LZCNodes.py", line 7, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

Cannot import M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\LZCNodes.py module for custom nodes: No module named 'tensorflow'
Traceback (most recent call last):
  File "M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\meh.py", line 11, in <module>
    from sd_meh import merge_methods
ModuleNotFoundError: No module named 'sd_meh'

Cannot import M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\meh.py module for custom nodes: No module named 'sd_meh'
Skip M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\preview_subselection.py module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.

[rgthree] Loaded 34 exciting nodes.
[rgthree] Will use rgthree's optimized recursive execution.

Traceback (most recent call last):
  File "M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\SyrianFalconNodes.py", line 1, in <module>
    from tkinter import Y
ModuleNotFoundError: No module named 'tkinter'

Cannot import M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\SyrianFalconNodes.py module for custom nodes: No module named 'tkinter'
WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
Error processing line 1 of M:\AI_Tools\ComfyUI_windows_portable\python_embeded\Lib\site-packages\zope.interface-6.2-py3.11-nspkg.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 186, in addpackage
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 570, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
Error processing line 1 of M:\AI_Tools\ComfyUI_windows_portable\python_embeded\Lib\site-packages\zope.interface-6.2-py3.11-nspkg.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 186, in addpackage
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 570, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
WAS Node Suite: Finished. Loaded 212 nodes successfully.

        "Your time is limited, don't waste it living someone else's life." - Steve Jobs

FETCH DATA from: M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
Error: OpenAI API key is invalid OpenAI features wont work for you
QualityOfLifeSuit_Omar92::NSP ready
FETCH DATA from: M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json
FETCH DATA from: M:\AI_Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json
```

**Versions:**  
Copy the output of the console (4 parts), like this:
```
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
```
```
Total VRAM 12288 MB, total RAM 16237 MB
Set vram state to: NORMAL_VRAM
```
```
[Crystools INFO] Crystools version: Latest version
[Crystools INFO] CPU: i5 12400F - OS: Windows 10
[Crystools INFO] GPU/s: 
[Crystools INFO] 0) NVIDIA GeForce RTX 3060 12GB
[Crystools INFO] NVIDIA Driver: Latest
```
```
### Loading: ComfyUI-Manager (V2.10.2)
### ComfyUI Revision: 2079[062483](2024-03-21)
```

**Additional context**

**Comment by crystian** [comment]
This kind of behavior should not be supported; you need to reinstall please, try to https://github.com/crystian/ComfyUI-Crystools?tab=readme-ov-file#installation

**Comment by nothingness6** [comment]
> This kind of behavior should not be supported; you need to reinstall please, try to https://github.com/crystian/ComfyUI-Crystools?tab=readme-ov-file#installation

I re-installed everything and it works. Thx.
