### ISSUE TITLE
AMD GPU solution

### ISSUE THREAD

**Issue by ricperry** [crystian/ComfyUI-Crystools#51]
**Is your feature request related to a problem? Please describe.**
Your project seems to still only be working on nvidia cards. Here is a solution to accomplish the same on AMD cards.

**Describe the solution you'd like**
Use the pyamdgpuinfo library: https://pypi.org/project/pyamdgpuinfo/

**Describe alternatives you've considered**
n/a

**Additional context**
You'd need to perform a test when the node is loaded to see what flavor you're going to use, nvidia or amd, then at the appropriate point in the code, call the correct function to get the usage data.

**Comment by ricperry** [comment]
Pretty simple:
```
>>> import pyamdgpuinfo
>>> n_devices = pyamdgpuinfo.detect_gpus()
>>> print(n_devices)
1
>>> first_gpu = pyamdgpuinfo.get_gpu(0)
>>> vram_usage = first_gpu.query_vram_usage()
>>> print(vram_usage)
11448217600
>>> gpu_load = first_gpu.query_load()
>>> print(gpu_load)
0.0
```

**Comment by PurplefinNeptuna** [comment]
thanks, this looks much better than amd's pyrsmi one,
I also tested it in non amd gpu and it looks ok.
I implemented it in my fork: #47 
sadly the temperature readings is only the overall temperature, not the junction/hotspot temperature which control throttling. amdsmi can get junction temperature.
pyamdgpuinfo can get gpu name unlike amdsmi though :laughing:

**Comment by crystian** [comment]
Sorry, this weekend, I'm going to review this

**Comment by ricperry** [comment]
Most recent update (6/7/2024) won't install (linux) (note, version number is unchanged):
```
[Crystools INFO] Crystools version: 1.12.0
~/ComfyUI/custom_nodes/ComfyUI-Crystools/nodes/image.py:313: SyntaxWarning: invalid escape sequence '\/'
  "Description": "More info: https:\/\/www.instagram.com\/crystian.ia", # "\/" is for escape / on json
[Crystools INFO] CPU: AMD Ryzen 9 5900X 12-Core Processor - Arch: x86_64 - OS: Linux 6.8.0-35-generic
[Crystools ERROR] Could not init pynvml.NVML Shared Library Not Found
[Crystools WARNING] No GPU with CUDA detected.
[Crystools ERROR] Could not pick default device.name 'amdsmi' is not defined
Traceback (most recent call last):
  File "~/ComfyUI/venv/lib/python3.12/site-packages/torch/cuda/__init__.py", line 635, in _raw_device_count_amdsmi
    amdsmi.amdsmi_init()
    ^^^^^^
NameError: name 'amdsmi' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/ComfyUI/nodes.py", line 1881, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "~/ComfyUI/custom_nodes/ComfyUI-Crystools/__init__.py", line 24, in <module>
    from .server import *
  File "~/ComfyUI/custom_nodes/ComfyUI-Crystools/server/__init__.py", line 1, in <module>
    from .monitor import *
  File "~/ComfyUI/custom_nodes/ComfyUI-Crystools/server/monitor.py", line 4, in <module>
    from ..general import cmonitor
  File "~/ComfyUI/custom_nodes/ComfyUI-Crystools/general/__init__.py", line 1, in <module>
    from .monitor import *
  File "~/ComfyUI/custom_nodes/ComfyUI-Crystools/general/monitor.py", line 66, in <module>
    cmonitor = CMonitor(1, True, True, True, True, True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/ComfyUI/custom_nodes/ComfyUI-Crystools/general/monitor.py", line 20, in __init__
    self.hardwareInfo = CHardwareInfo(switchCPU, switchGPU, switchHDD, switchRAM, switchVRAM)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/ComfyUI/custom_nodes/ComfyUI-Crystools/general/hardware.py", line 44, in __init__
    self.GPUInfo = CGPUInfo()
                   ^^^^^^^^^^
  File "~/ComfyUI/custom_nodes/ComfyUI-Crystools/general/gpu.py", line 70, in __init__
    self.cudaAvailable = torch.cuda.is_available()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/ComfyUI/venv/lib/python3.12/site-packages/torch/cuda/__init__.py", line 122, in is_available
    return device_count() > 0
           ^^^^^^^^^^^^^^
  File "~/ComfyUI/venv/lib/python3.12/site-packages/torch/cuda/__init__.py", line 838, in device_count
    nvml_count = _device_count_amdsmi() if torch.version.hip else _device_count_nvml()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "~/ComfyUI/venv/lib/python3.12/site-packages/torch/cuda/__init__.py", line 760, in _device_count_amdsmi
    raw_cnt = _raw_device_count_amdsmi()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/ComfyUI/venv/lib/python3.12/site-packages/torch/cuda/__init__.py", line 636, in _raw_device_count_amdsmi
    except amdsmi.AmdSmiException as e:
           ^^^^^^
NameError: name 'amdsmi' is not defined

```

**Comment by BroderPeters** [comment]
Love the tool, but was a bit sad to find out that it won't fully work with my AMD graphics card.
Is there any update or estimation on this issue?

**Comment by crystian** [comment]
I tried it, but the dependency pyamdgpuinfo breaks the installation on windows, so, I can't allow that, sorry :(

check: https://github.com/crystian/ComfyUI-Crystools/pull/76

If you are a AMD & linux user, you can install manually with this line:
```
git clone -b AMD https://github.com/crystian/ComfyUI-Crystools.git
```

**Comment by ricperry** [comment]
Use of AMDSMI on linux completely trahses my ComfyUI install. I struggled for 2 days to figure out what was causing it. Ended up just having to remove Crystools and rebuild my venv.
