### ISSUE TITLE
Exception in thread Thread-11 (startMonitorLoop)

### ISSUE THREAD

**Issue by JimWang151** [crystian/ComfyUI-Crystools#85]
**Describe the bug**  
I installed comfyui_crystal plugin via comfyui manager.But when loading this plugin the error occured .
Below is error msg:

**_Exception in thread Thread-11 (startMonitorLoop):_**
Traceback (most recent call last):
  File "D:\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "D:\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ComfyUI\custom_nodes\ComfyUI-Crystools\general\monitor.py", line 31, in startMonitorLoop
    asyncio.run(self.MonitorLoop())
  File "D:\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-Crystools\general\monitor.py", line 35, in MonitorLoop
    data = self.hardwareInfo.getStatus()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-Crystools\general\hardware.py", line 73, in getStatus
    hdd = psutil.disk_usage(self.whichHDD)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Python312\Lib\site-packages\psutil\__init__.py", line 2005, in disk_usage
    return _psplatform.disk_usage(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Python312\Lib\site-packages\psutil\_pswindows.py", line 280, in disk_usage
    total, free = cext.disk_usage(path)
                  ^^^^^^^^^^^^^^^^^^^^^
**_SystemError: argument 1 (impossible<bad format char>)_**

[Crystools INFO] Crystools version: 1.15.0
[Crystools INFO] CPU: 13th Gen Intel(R) Core(TM) i9-13900HX - Arch: AMD64 - OS: Windows 11
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4060 Laptop GPU
[Crystools INFO] NVIDIA Driver: 555.99
### Loading: ComfyUI-Impact-Pack (V5.18.1)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V0.82)
Total VRAM 8188 MB, total RAM 16104 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.27
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : native

Thanks for you attention.

**Comment by PurplefinNeptuna** [comment]
can you check psutil version? python 3.12 seems have buggy psutils

**Comment by JimWang151** [comment]
> can you check psutil version? python 3.12 seems have buggy psutil

Thanks .I will try and leave msg here.

**Comment by linkally** [comment]
> > can you check psutil version? python 3.12 seems have buggy psutil
> 
> Thanks .I will try and leave msg here.

I meet the same issue, how about it then?
