### ISSUE TITLE
Error during Crystools installation

### ISSUE THREAD

**Issue by magicpigomg** [crystian/ComfyUI-Crystools#95]
**Describe the bug**  
Error during Crystools installation

**Screenshots**  
![Screenshot_6](https://github.com/user-attachments/assets/65e60471-4c74-4462-9d60-ebf51cd4a5be)
![Screenshot_5](https://github.com/user-attachments/assets/71c5a4da-967e-41be-a6a8-f61b99fbb495)
![Screenshot_4](https://github.com/user-attachments/assets/41a082d6-e366-4649-99a1-1c21169e1890)

**Error in console:**  
[Crystools INFO] Crystools version: 1.15.1
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools\__init__.py", line 24, in <module>
    from .server import *
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools\server\__init__.py", line 1, in <module>
    from .monitor import *
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools\server\monitor.py", line 4, in <module>
    from ..general import cmonitor
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools\general\__init__.py", line 1, in <module>
    from .monitor import *
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools\general\monitor.py", line 5, in <module>
    from .hardware import CHardwareInfo
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools\general\hardware.py", line 4, in <module>
    from .gpu import CGPUInfo
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools\general\gpu.py", line 6, in <module>
    from pyrsmi import rocml
ModuleNotFoundError: No module named 'pyrsmi'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools module for custom nodes: No module named 'pyrsmi'

**Versions:**  
```
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
```
```
Total VRAM 12282 MB, total RAM 31895 MB
Set vram state to: NORMAL_VRAM
```
```
[Crystools INFO] Crystools version: 1.15.1
```
```
### Loading: ComfyUI-Manager (V2.48.2)
### ComfyUI Revision: 2425 [c24f8973] | Released on '2024-07-31'
```

**Comment by magicpigomg** [comment]
> Hi, I had the same problem. You can install pyrmsi by yourself with 'pip install pyrsmi', it seems to work well.

Hi, I deleted and reinstalled, but the error, as I understand it, remains. Maybe a screenshot will help to better understand what's wrong.

Requirement already satisfied: pyrsmi in c:\users\artem\appdata\local\programs\python\python310\lib\site-packages (0.0.6)

![Screenshot_7](https://github.com/user-attachments/assets/c330d16c-2f62-4fc2-a441-f4aeb56e8b87)

**Comment by crystian** [comment]
Crystools Updated! Please try to updated (should be 1.16.0)

**Comment by mroberts1** [comment]
I am still having this issue in May 2025... Always one node missing

<img width="582" alt="Image" src="https://github.com/user-attachments/assets/348037a9-28ab-408e-b704-ce654f25bce8" />
